### ISSUE TITLE
/fdfe/sync

### ISSUE THREAD

**Issue by 1268** [3052/google#20]
from here:

https://github.com/1268/google/commit/9ad93409cda644a3988867ae6f716a0db27c5d47

Let me help you a bit, I didnt find everything yet, but maybe u can:
Create a request to (you can clear storage/cache and reopen gplay) :
`https://play-fe.googleapis.com/fdfe/toc`
With both device-id.

Check the response from a device id created by us:
```
  "1": {
    "6": {
      "11": 1, 
      "22": "EAEYACICUFRCFQoFUFQtMTESDAjLquWoBhCojufKA0oSCgJQVBIMCMuq5agGEIC86soDUkoKFTEwNzM5OTA0MDExNjMyNTE3NTc3ORABGgwIjMzRpwYQoP_ErwEyDAi6y7inBhDAqorrAToKR2VueW1vYmlsZUIHdmJveDg2cFgA"
    }
  },
```

vs the request with a device id registered  by gplay
```
    "6": {
      "1": [
        {
          "1": 3, 
          "2": "Apps", 
          "3": "subnavHome?c=3", 
          "4": "My apps & games", 
          "7": "Shop apps", 
          "8": 3
        }
        .....
```
The fields are registered as 
`requiresUploadDeviceConfig` and `cookie`
(X-Dfe-Cookie?)
I already tested `https://www.googleapis.com/experimentsandconfigs/v1/getExperimentsAndConfigs?r=12&c=128` and got the same error response

**Comment by 1268** [comment]
https://github.com/1268/google/issues/19

**Comment by 1268** [comment]
@GRodrig I am still researching, but I think the problem is that you need to do `/fdfe/uploadDeviceConfig` after `/checkin`. I used to do that, but I pulled the `uploadDeviceConfig` request because it wasn't needed at the time, but it seems its required with `/fdfe/acquire`

**Comment by GRodrig** [comment]
@1268 I always had that request + kept the header with the respective token, I couldn't make `/acquire` work.
In the most recent versions I can't find `/fdfe/uploadDeviceConfig` so I assume it has been deprecated/replaced

**Comment by 1268** [comment]
currently I am targeting Google Services Framework 21, I might increase this later. what version are you using?

**Comment by GRodrig** [comment]
30

**Comment by 1268** [comment]
yeah sorry I cannot provide any support for anything over Google Services Framework 21 at this time. I fixed the auth code already:

https://github.com/1268/google/blob/33511336a6680a0f87cafee9799c57fc5ccf0a20/play/auth.go#L18-L25

so now I am working on updating to Google Play Store version 11, which uses `/fdfe/acquire`

**Comment by 1268** [comment]
@GRodrig FYI I have now reversed the `/fdfe/acquire` code. I am able to do:

 the `/checkin`, `/fdfe/uploadDeviceConfig`, `/fdfe/acquire`, `/fdfe/delivery` flow for Google Play

I will try to post the code soon

**Comment by 1268** [comment]
https://github.com/1268/google/issues/21

**Comment by 1268** [comment]
OK my code now supports API 26, so I am considering newer options. can you clarify what version of Google Play Store you were using?

**Comment by 1268** [comment]
OK looks like starting with Google Play Store 29, `/fdfe/uploadDeviceConfig` is no longer used. I will do more testing

**Comment by 1268** [comment]
after further testing, simply swapping the `X-DFE-Device-ID` does the trick, which means that either `/checkin` is different, or maybe `/fdfe/uploadDeviceConfig` request was replaced by another request.

**Comment by 1268** [comment]
OK it looks like either `/fdfe/uploadDeviceConfig` was replaced by `/fdfe/sync`, or maybe something is different about `/checkin`. will keep looking

**Comment by 1268** [comment]
OK it seems that `/fdfe/uploadDeviceConfig` was replaced by `/fdfe/sync`

I will see about coding the new request

**Comment by 1268** [comment]
OK I think `/fdfe/sync` is done now:

~~~
> play -device
POST https://android.clients.google.com/checkin
Sleep(9*time.Second)
POST https://android.clients.google.com/fdfe/sync

> play -d com.simonandschuster.pimsleur.unified.android
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.simonandschuster.pimsleur.unified.android
creator: Simon & Schuster
file: APK APK APK APK
installation size: 83.08 megabyte
downloads: 1.76 million
offer: 0 USD
requires: Android 6.0 and up
title: Pimsleur: Language Learning
upload date: Sep 21, 2023
version: 5.0
version code: 423

> play -d com.simonandschuster.pimsleur.unified.android -v 423
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/delivery?doc=com.simonandschuster.pimsleur.unified.android&vc=423
panic: acquire

> play -d com.simonandschuster.pimsleur.unified.android -a
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/fdfe/acquire

> play -d com.simonandschuster.pimsleur.unified.android -v 423
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/delivery?doc=com.simonandschuster.pimsleur.unified.android&vc=423
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0RCEjlHaZ3yuEW93fffPKLkZJaMomxdWuAQHTXdSL0TbQmsxRCT4ZQiB9OoEDGB5FGTBdlOcOpJrnYBsoUPX4KINqor4L-ANbrAN-bVnc5w5fEnzD0xWk9p2b_bRuXjtpQyfgv-6-ZhBtoTjQrHMyLiHaIclMSiCO2dPoVE6QJzEAbRPybuiCTUUidcYof38G52XaxK23ZMQGad4uKEGPQic8qwZx3R1lRpsZbyjD-_6RVdWcY5YtptKMUOyLQuRZUhrwN7wG-CKM8V9zt6FLCMWg7kA6ZGy1HpD5mtl3CmUR-O8dCBGviDE2iTZuUCscbrDIP2AU9dWP4zOcQekrYLe89VOrkajSMPbkfGiNAVMR_kLyI1ITx-RhWdQ86WVtgplzipvFsIDByGPCnh6vCLM1Qj4Fxtyc2tUPssf-w9Yvuyea5lKO3MlOCyM577QSXMsymlUms-zHwUPrX2kObX&cpn=zXIgG4KlsFnwPLko
GET https://rr3---sn-q4fl6n6y.gvt1.com/play-apps-download-default/download/by-id/AF3DWBfkGpzLDiMDFxTo4XhicYUCStAldu_bYSMV_CIXaT0cws5Wx62R-kAHCY_mDBacuEMJ62unLgnEEnb-fyM5HptVh44HOo6YlEdckv_G3v9cN40U3dYOvOqHPIZgv_-6UDDVtDg4oP13YN-Kb6Ixi7jtDNyh-g?cpn=zXIgG4KlsFnwPLko&ctier=L&fvip=2&initcwndbps=1277500&mh=-N&mm=31,26&mn=sn-q4fl6n6y,sn-a5mekn6s&ms=au,onr&mt=1696218342&mv=m&mvi=3&pl=16&expire=1696391488&ip=72.181.23.38&ipbits=0&sparams=expire,ipbits,ip,q:,initcwndbps,mh,mm,mn,ms,mv,mvi,pl,ctier&signature=4EFB506FC5EC91114BE4CA9CE7524087DF709CC4.48269B2EB5C572F86EFDEEDFB8F632FAB7ABFFEF&key=am3
~~~

**Comment by 3052** [comment]
https://github.com/3052/google/issues/26

**Comment by 3052** [comment]
looks like I didn't do enough testing:

~~~
> go run . -d com.atomczak.notepat -a
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/fdfe/acquire

> go run . -d com.google.android.youtube -a
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/fdfe/acquire
panic: Error
Your device is not compatible with this item.
~~~

**Comment by 3052** [comment]
OK I think I figured it out -  `glEsVersion` needs to be specified for some apps. I was already doing that for `/checkin`, but it seems `/fdfe/sync` needs it too https://developer.android.com/guide/topics/manifest/uses-feature-element#glEsVersion

I removed `/fdfe/uploadDeviceConfig` and added `/fdfe/sync` and pushed a new tag, hopefully everything is good now. all that should be different from the previous `/fdfe/sync` is the GL ES version is now included

https://github.com/3052/google/blob/f9ab0ec4b37d57b207e0de95d25f82ccbc41a1ee/play/sync.go#L44-L48
