### ISSUE TITLE
Your device is not compatible with this item

### ISSUE THREAD

**Issue by 1268** [3052/google#26]
~~~
> go run . -d com.atomczak.notepat -a
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/fdfe/acquire

> go run . -d com.google.android.youtube -a
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/fdfe/acquire
panic: Error
Your device is not compatible with this item.
~~~

**Comment by 1268** [comment]
~~~
> go run . -d com.atomczak.notepat -a
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/fdfe/acquire

> go run . -d com.google.android.youtube -a
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/fdfe/acquire
panic: Error
Your device is not compatible with this item.
~~~

**Comment by phynicz** [comment]
How can this device compatibility issue be fixed?

**Comment by 1268** [comment]
I took a break yesterday because my primary donor has not paid for October. hopefully that gets resolved today. otherwise we might have a big problem.

**Comment by victorolaiya** [comment]
Oh I hope that has been resolved! I think the project is amazing!

**Comment by 1268** [comment]
thats nice, but neither one of the commenters here have even starred the repo, never mind donating.

and no the issue has not been resolved. at this point I have lost most of my motivation to continue, hopefully tomorrow the situation will be fixed, but its not looking good.

**Comment by phynicz** [comment]
I just starred it, but If we want to donate how do we contribute.

**Comment by 1268** [comment]
https://paypal.com/donate?hosted_button_id=UEJBQQTU3VYDY

**Comment by 3052** [comment]
https://github.com/3052/google/issues/20
