### ISSUE TITLE
Install/build instructions??

### ISSUE THREAD

**Issue by DerivativeOfLog7** [3052/google#28]
I'm completely new to Go and can't for the life of me figure out how to use this repo

**Comment by 3052** [comment]
https://github.com/3052/google#support

**Comment by DerivativeOfLog7** [comment]
> https://github.com/3052/google#support

"cd into the individual folders and run go build in the sufvolders"
There it is, in 30 seconds

**Comment by 3052** [comment]
> [removed]

removed instructions

> There it is, in 30 seconds; tho I had to figure it out by chance because to me it seems very counter intuitive (but this isn't this repo's fault)

thats 30 seconds of my time. my time is not free.

> Build instructions in the readme are always welcome either way

no thanks. I removed the instructions on purpose, because that's just me giving out free help. I think I have been generous enough giving out the software already.

**Comment by 3052** [comment]
@DerivativeOfLog7 congrats, you are now banned from my repos
