### ISSUE TITLE
universal apk

### ISSUE THREAD

**Issue by andryan** [3052/google#29]
hi,
is it possible to download the universal apk instead?

**Comment by 3052** [comment]
what is that?

**Comment by andryan** [comment]
sorry for the late reply. universal apk is the combined apk files that can be installed universally across any of the supported platforms. at the moment the tool downloads multiple apks and are not immediately usable for installation

**Comment by 3052** [comment]
https://github.com/3052/google#support

**Comment by andryan** [comment]
![Uploading IMG_1072.png…]()

**Comment by 3052** [comment]
I dont mind, but I never used that stuff. which one is good?

**Comment by andryan** [comment]
tether (usdt) on polygon/tron/bnb, perhaps?

**Comment by 3052** [comment]
I dont know what any of that is. got a URL?

**Comment by andryan** [comment]
the easiest would be to create an account at one of the top crypto exchanges, either binance or coinbase or bybit or okx. you will get a wallet address upon being registered there. share that wallet address of yours

**Comment by 3052** [comment]
binance? is that a joke?

https://wikipedia.org/wiki/Binance#United_States

**Comment by andryan** [comment]
why is it a joke? the world is not only the US. binance is the largest crypto exchange in the world, https://coinmarketcap.com/rankings/exchanges/

**Comment by 3052** [comment]
https://wikipedia.org/wiki/Binance#United_Kingdom

**Comment by andryan** [comment]
I mentioned 4 names and not sure why you are fixated on binance

**Comment by 3052** [comment]
please name the current best option in your opinion, and provide URL. remember you came to me for help, not the reverse, so you should make this process simple for me. I am not interested in researching a bunch of crypto options at this time. my main focus is not Google Play, as the code here is more or less "done".

**Comment by andryan** [comment]
if you are in the US, use Coinbase. create an account and share your ERC-20 or TRC-20 wallet address on your Tether/USD Coin balance on Coinbase

**Comment by 3052** [comment]
that website is a piece of shit. I went through the trouble of signing up, click Send & Receive, click Receive, click the copy icon under BTC address (Bitcoin) and nothing is copied to the clipboard.

> ![Untitled](https://github.com/3052/google/assets/147215885/ea3f64e6-285e-424c-8711-900a4858311b)

**Comment by 3052** [comment]
OK I think this is it:

3KizRDsjBEPwFym5YaQ7UwHLKBZf4LGMzE

**Comment by andryan** [comment]
sorry I just had reinstalled coinbase to remember what the interface looks like. can you go to USDC, tap on Receive and change the network (Ethereum) to Polygon? the wallet address should be 0x...

**Comment by 3052** [comment]
ETH address (Ethereum)
0xB614Ff822c8Df557dd4714f80Cd280Bc3887390F

**Comment by andryan** [comment]
check your coinbase usdc wallet balance

**Comment by 3052** [comment]
sorry my standard fee is 99 USD or equivalent

**Comment by andryan** [comment]
$99 to answer a question??

**Comment by 3052** [comment]
OK I have been MOOOORE than patient. enough is enough. locking this. if you are interested in paid support, contact me:

https://github.com/3052/google#contact

otherwise leave me alone.
