### ISSUE TITLE
[Bug] Old application version

### ISSUE THREAD

**Issue by oifj34f34f** [3052/google#34]
https://play.google.com/store/apps/details?id=com.google.android.apps.translate

<pre>
$ ./play -a com.google.android.apps.translate
* method:POST URL:https://android.googleapis.com/auth
* method:GET URL:https://android.clients.google.com/fdfe/details?doc=com.google.android.apps.translate
downloads: 1.32 billion
files: APK
name: Google Translate
offered by: Google LLC
price: 0 RUB
requires: 4.0.3 and up
size: 18.78 megabyte
updated on: <b>Oct 14, 2015</b>
version code: 44000163
version name: <b>4.4.0.RC01.104701208</b>
</pre>

**Comment by 3052** [comment]
https://github.com/3052/google#support

**Comment by oifj34f34f** [comment]
I found out it's because of the X-DFE-Device-ID
