### ISSUE TITLE
auth : panic: 403 Forbidden

### ISSUE THREAD

**Issue by irpr0** [3052/google#36]
hello

after compile and run command i give error : 
`command : play -o .....`

err : 
```
msg=POST URL=https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
```

i capture the request and send by curl :
```

Req : 

POST /auth HTTP/2
Host: android.googleapis.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Dnt: 1
Content-Type: application/x-www-form-urlencoded
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: cross-site
Content-Length: 117
Te: trailers

ACCESS_TOKEN=1&Token=oauth2_4%2FXXX&service=ac2dm
```

Response : 

```
HTTP/2 403 Forbidden
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Sun, 07 Apr 2024 16:08:01 GMT
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site
Content-Type: text/html; charset=utf-8
Cross-Origin-Opener-Policy: same-origin
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Server: GSE
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Comment by 3052** [comment]
I just ran the above on current commit, and everything is working fine. I did add some code to give a better error message:

https://github.com/3052/google/blob/ab7239093498a0156772b7638059be1151d8c274/play/auth.go#L23-L27

but sorry I think thats all I can do for now. if you know why its failing I am happy to help, but I need to be able to reproduce the issue

**Comment by irpr0** [comment]
thanks for update
my problem fixed ... BadAuthentication <

i find another problem but its not important .

when i run it on windows .. see this error  :

`panic: open C:\Users\sys1/google-play/x86.bin: The system cannot find the file specified.`

need to replace / with \ for windows ...

**Comment by 3052** [comment]
OK issue is corrected:

https://github.com/3052/google/blob/e8460f6ba6fa00586578704318f9538fc83c73ba/internal/play/main.go#L24-L32
