### ISSUE TITLE
Error=BadAuthentication

### ISSUE THREAD

**Issue by funcolin** [3052/google#38]
I filled in "play - o" correctly, but reported a BadAuthentication error

The oauth token is obtained after logging in from "accounts. Google. com/embedded/setup/v2/android"

<img width="955" alt="image" src="https://github.com/3052/google/assets/150231815/dc79b05b-c9ba-4b23-94ff-49c3f7877cba">

**Comment by 3052** [comment]
https://github.com/3052/google#support

**Comment by funcolin** [comment]
> https://github.com/3052/google#support

How much does it take to donate at least?

**Comment by 3052** [comment]
contact me privately
