### ISSUE TITLE
A newbie wants to know how to execute a project :'(

### ISSUE THREAD

**Issue by FEXAQAQ** [3052/google#42]
I have never come across GO-related languages, and I would like to confirm my execution steps with you.

Step1. Install GO
Step2. Clone project
Step3. Switch to the project and find main.go
Step4. Use go run main.go command
Step5. Appears after execution
# command-line-arguments
.\main.go:60:19: f.do_acquire undefined (type flags has no field or method do_acquire)
.\main.go:65:19: f.do_delivery undefined (type flags has no field or method do_delivery)
.\main.go:70:28: f.do_details undefined (type flags has no field or method do_details)
.\main.go:77:16: f.do_auth undefined (type flags has no field or method do_auth)
.\main.go:82:16: f.do_device undefined (type flags has no field or method do_device)

Can anyone guide me~  I will be very grateful to you :)

**Comment by 3052** [comment]
https://github.com/3052/google#support

**Comment by FEXAQAQ** [comment]
> https://github.com/3052/google#support

OK ! I'm sorry ~

**Comment by 01101sam** [comment]
> > https://github.com/3052/google#support
> 
> OK ! I'm sorry ~

## Windows

```shell
go build -o play.exe 154.pages.dev/google/internal/play
./play.exe -h
```

## Linux

```shell
go build -o play 154.pages.dev/google/internal/play
chmod +x play
./play -h
```

Not sure why author not adding this simple command in the README, but that's working for now

**Comment by 3052** [comment]
The link above is pretty clear 

> because of repeated abuse, as of november 5 2023, I no longer offer free discussion of this software.

Since @01101sam blatantly ignored it, they are now banned from my repos. Good game.
