### ISSUE TITLE
Single apk option still works?

### ISSUE THREAD

**Issue by hitabi** [3052/google#44]
Single apk option stopped working for me. It output two lines "INFO POST" and one "INFO GET" and returns to terminal without any error message.

**Comment by 3052** [comment]
example command?

**Comment by hitabi** [comment]
For example play -i com.twitter.android -c 310551000 -s

**Comment by 3052** [comment]
thats normal. same for APK Mirror:

https://apkmirror.com/apk/x-corp/twitter/twitter-10-55-1-release-0-release

the single APK option has always been a hack, using an older version of Google Play Store:

https://github.com/3052/google/blob/f9afc5880774d3519829871e536ea1447d758e14/play/play.go#L142-L148

so if it doesn't work you just have to deal with it, and its possible it could stop working for all apps at any time. if anyone find a better method to get single APK, I am happy to add it.

**Comment by hitabi** [comment]
About one or two months ago it was working for me for all apps. Thanks for the quick responses. You can close the issue if you want.
