### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by eternal-sorrow** [3052/google#45]
`go build` in the root directory says "no Go files in /path/to/google`

`go build ./play` does something, but no binary is found anywhere after it is finished.

**Comment by notlit69** [comment]
go to internal > play folder and run `go build play.go`

**Comment by 3052** [comment]
@notlit69 congrats you are now banned

**Comment by 3052** [comment]
https://github.com/3052/google#support

**Comment by eternal-sorrow** [comment]
Alright then, I guess you're not interested in having your software used by anyone except yourself. The question is, why is it even published here.

**Comment by 3052** [comment]
just because you're cant figure it out - doesn't mean its worthless. thats why people have starred and forked the repo.

**Comment by oifj34f34f** [comment]
@eternal-sorrow 

```sh
$ git clone https://github.com/3052/google google-play
$ cd google-play/internal/play/
$ go build
```

**Comment by 3052** [comment]
@oifj34f34f congrats you have been banned

**Comment by 3052** [comment]
as mentioned before:

https://github.com/3052/google#support

**Comment by eternal-sorrow** [comment]
Why though? What is worse about this place compared to any other?

**Comment by 3052** [comment]
I don't want the answers to these questions being public information. I have spent literal years writing this software, and offer it for free. that's good enough. if you don't like my terms, don't use my software. write your own, or fork the repo, or use something else, I don't care. I am under no obligation to you or anyone to provide any information or answer any questions. 

I don't even have to publish a Readme, I do that as a courtesy. its clear you have no idea how open source works, given your entitled attitude, and lack of any public repos:

https://github.com/eternal-sorrow?tab=repositories

where is your code homie?

**Comment by john4756246** [comment]
@eternal-sorrow

After clicking the "I agree," press F12, click the "Application" tab (you may need to click `>>` first), expand the "Cookies" section in the left sidebar, select the URL of the site, find the cookie named "oauth_token" in the list, and then double-click on its value to copy it.

**Comment by 3052** [comment]
@john4756246 congrats you've been banned - I can keep doing this all day people
