### ISSUE TITLE
APK cannot be installed

### ISSUE THREAD

**Issue by zhengjianyang** [3052/google#49]
Why can't the APK I downloaded install properly? Can you install it without issues?

**Comment by 3052** [comment]
which one

**Comment by zhengjianyang** [comment]
. -i org.telegram.messenger 
. -i org.telegram.messenger  -a
. -i org.telegram.messenger  -v 54732

These are the steps I took

**Comment by 3052** [comment]
works fine

![Untitled](https://github.com/user-attachments/assets/df2618ce-bb8b-4085-8cc7-72ee1c7d3a8a)

**Comment by zhengjianyang** [comment]
Is it possible that the issue is because my Google account is not linked to an Android device? I'm trying to find an Android phone to link it and try again.

**Comment by 3052** [comment]
https://github.com/3052/google#support
